[[main]]
none = "none"

[[main]]
name = "Career Journey"
pageRef = "career-journey"
identifier = "AlDb3FSBlF"
weight = 1

[[main]]
name = "Contact"
pageRef = "contact"
identifier = "pweiP3R1De"
weight = 2

[[footer]]
none = "none"
