[[main]]
none = "none"

[[main]]
name = "Career Journey"
pageRef = "career-journey"
identifier = "AlDb3FSBlF"
weight = 1

[[main]]
name = "Education"
pageRef = "education"
identifier = "zMF1njsQl2"
weight = 2

[[main]]
name = "Contact"
pageRef = "contact"
identifier = "pweiP3R1De"
weight = 3

[[footer]]
none = "none"

[[footer]]
name = "Terms & Conditions"
pageRef = "terms-and-conditions"
identifier = "Z4DOTLbDTe"
weight = 9999

[[footer]]
name = "Privacy Policy"
pageRef = "privacy-policy"
identifier = "zBirKldy3I"
weight = 9999
