[[main]]
none = "none"

[[main]]
name = "Posts"
pageRef = "posts"
identifier = "posts"
weight = 1

[[main]]
name = "About Me"
pageRef = "#"
identifier = "about-me"
weight = 10

[[main]]
name = "Career Journey"
parent = "about-me"
pageRef = "career-journey"
identifier = "career-journey"
weight = 11

[[main]]
name = "Education"
parent = "about-me"
pageRef = "education"
identifier = "education"
weight = 12

[[main]]
name = "Contact"
pageRef = "contact"
identifier = "contact"
weight = 99

[[footer]]
none = "none"

[[footer]]
name = "Terms & Conditions"
pageRef = "terms-and-conditions"
identifier = "terms-and-conditions"
weight = 9999

[[footer]]
name = "Privacy Policy"
pageRef = "privacy-policy"
identifier = "privacy-policy"
weight = 9999
